apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventory-serviceaccount
  annotations:
    azure.workload.identity/client-id: 0f8a60ed-3968-4f83-9d85-f60a288532e0
  labels:
    azure.workload.identity/use: "true"