apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-deployment
spec:
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: inventory-serviceaccount
      containers:
      - name: inventory
        image: playeconomyaxsg1.azurecr.io/play.inventory:1.0.4.1
        env:
          - name: ServiceSettings__MessageBroker
            value: SERVICEBUS
          - name: ServiceSettings__KeyVaultName
            value: playeconomyaxsg1
          - name: ServiceSettings__Authority
            value: https://playeconomyaxsg1.eastus.cloudapp.azure.com/identity-svc
        resources:
          limits:
            memory: "128Mi"
            cpu: "150m"
        ports:
        - containerPort: 5004
        livenessProbe:
          httpGet:
            path: /health/live
            port: 5004
          initialDelaySeconds: 30
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 5004
          initialDelaySeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  type: ClusterIP
  selector:
    app: inventory
  ports:
  - port: 80
    targetPort: 5004

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventory-serviceaccount
  annotations:
    azure.workload.identity/client-id: 1ce5e3a0-168f-4cca-bb6b-f7c28efe8407
  labels:
    azure.workload.identity/use: "true"